ci(branches): enable publishing docker images for branches #621
* ci(actions): allow create branch image tags
* docs: update image ref to github public registry
* chore(examples): remove kubernetes example since it's outdated
* ci(branch): run only when meaningful changes

diff --git a/.github/actions/publish-image/action.yml b/.github/actions/publish-image/action.yml
--- a/.github/actions/publish-image/action.yml
+++ b/.github/actions/publish-image/action.yml
@@ -1,9 +1,6 @@
 name: Build and publish docker images
 description: Builds and publish docker images to github registry
 inputs:
-  github-token:
-    description: Github secret secrets.GITHUB_TOKEN
-    required: true
   image-name:
     description: Image name for example lh-server
     required: true
@@ -13,29 +10,80 @@ inputs:
   dockerfile:
     description: Relative route of Dockerfile
     required: true
+  registry:
+    description: Either github or ecr
+    default: github
+  github-token:
+    description: Github secret secrets.GITHUB_TOKEN required only if registry is github
+    default: ""
+  prefix:
+    description: prefix to be appended to image tag ex brach-
+    default: ""
 
 runs:
   using: composite
   steps:
+    - name: Registry not recognized
+      shell: bash
+      if: ${{ inputs.registry != 'github' && inputs.registry != 'ecr' }}
+      run: |
+        echo "Registry not recognized, it should be github or ecr"
+        exit 1
+
+    - name: github-token is required
+      shell: bash
+      if: ${{ inputs.registry == 'github' && inputs.github-token == '' }}
+      run: |
+        echo "github-token is required when registry is github"
+        exit 1
+
+    - name: Set up QEMU
+      uses: docker/setup-qemu-action@v3
+
+    - name: Set up Docker Buildx
+      uses: docker/setup-buildx-action@v3
+
     - name: Log in to github registry
+      if: ${{ inputs.registry == 'github'}} 
       uses: docker/login-action@v3
       with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ inputs.github-token }}
-    
-    - name: Set up QEMU
-      uses: docker/setup-qemu-action@v3
-      
-    - name: Set up Docker Buildx
-      uses: docker/setup-buildx-action@v3
+
+    - name: Configure AWS credentials
+      if: ${{ inputs.registry == 'ecr' }} 
+      uses: aws-actions/configure-aws-credentials@v4
+      with:
+        role-to-assume: arn:aws:iam::637423582379:role/GithubActions-ECR
+        role-session-name: gha-ecr
+        aws-region: us-west-2
+
+    - name: Login to Amazon ECR
+      id: login-ecr
+      if: ${{ inputs.registry == 'ecr' }} 
+      uses: aws-actions/amazon-ecr-login@v2
+
+    - name: Set DOCKER_IMAGE to github
+      if: ${{ inputs.registry == 'github'}} 
+      shell: bash
+      run: |
+        echo DOCKER_IMAGE=ghcr.io/${{ github.repository }}/${{ inputs.image-name }} >> $GITHUB_ENV
+
+    - name: Set DOCKER_IMAGE to ecr
+      if: ${{ inputs.registry == 'ecr' }} 
+      shell: bash
+      run: |
+        echo DOCKER_IMAGE=${{ steps.login-ecr.outputs.registry }}/${{ inputs.image-name }} >> $GITHUB_ENV
 
     - name: Extract metadata (tags, labels) for Docker
-      id: meta
       uses: docker/metadata-action@v5
+      id: meta
       with:
         images: |
-          ghcr.io/${{ github.repository }}/${{ inputs.image-name }}
+          ${{ env.DOCKER_IMAGE }}
+        flavor: |
+          prefix=${{ inputs.prefix }}
 
     - name: Build and push Docker images
       uses: docker/build-push-action@v5
@@ -45,3 +93,8 @@ runs:
         push: true
         tags: ${{ steps.meta.outputs.tags }}
         labels: ${{ steps.meta.outputs.labels }}
+    
+    - name: Annotate image
+      shell: bash
+      run: |
+        echo "::notice title=Published Docker Image::${{ steps.meta.outputs.tags }}"
